name: chambeape
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  card_swiper: ^3.0.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  dash_chat_2: ^0.0.20
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.5
  gcloud: ^0.8.12
  get: ^4.6.6
  go_router: ^14.1.1
  googleapis_auth: ^1.6.0
  http: ^1.1.0
  http_mock_adapter: ^0.6.1
  http_parser: ^4.0.2
  image_picker: ^1.1.0
  intl: ^0.19.0
  mime: ^1.0.5
  mockito: ^5.4.4
  path: ^1.9.0
  photo_view: ^0.15.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  stomp_dart_client: ^2.0.0
  timezone: ^0.9.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gcloud_credentials.json
