const List<String> categories = [
  'Jardinería',
  'Educación',
  'Música',
  'Reparación de electrodomésticos',
  'Fontanería',
  'Carpintería',
  'Limpieza doméstica',
  'Pintura',
  'Diseño gráfico',
  'Consultoría financiera',
  'Traducción e interpretación',
  'Fotografía',
  'Entrenamiento personal',
  'Masajes terapéuticos',
  'Cuidado de mascotas',
  'Coaching',
  'Cocina',
  'Otro',
];

const List<String> departaments = [
  'Departamento',
  'Lima',
  'Ancash',
  'Apurimac',
  'Arequipa',
  'Ayacucho',
  'Cajamarca',
  'Callao',
  'Cusco',
  'Huancavelica',
  'Huanuco',
  'Ica',
  'Junin',
  'La Libertad',
  'Lambayeque',
  'Lima Region',
  'Loreto',
  'Madre de Dios',
  'Moquegua',
  'Pasco',
  'Piura',
  'Puno',
  'San Martin',
  'Tacna',
  'Tumbes',
  'Ucayali',
];
